server:
  port: 8888

#设置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.55.129.110:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: XXXXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
  #设置时区
  jackson:
    time-zone: GMT+8
  #设置缓存数据
  data:
    redis:
      host: 114.55.129.110
      port: 6379
      password: XXXXXX
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  type-aliases-package: com.coder.mall.user.domain.domain

springdoc:
  default-flat-param-object: true

#配置阿里云的短信服务
aliyun:
  sms:
    access-key-id: LTAI5tPu4kBppVuEJhabJhmb
    access-key-secret: 5kHMRKSakMM803YEww9wgCXxi9IZze
    endpoint: dysmsapi.aliyuncs.com